### ISSUE TITLE
Could not find scrollreveal typescript file

### ISSUE THREAD

**Issue by pryanwong** [tinesoft/ng2-scrollreveal#4]
I had to run the following command in order to get ng2-scrollreveal to work properly.

npm install @types/scrollreveal@0.0.2

**Comment by tinesoft** [comment]
Hi @pryanwong,

The typings for `scollrevealjs` are not included in the package of this library and are only used internally. 
But all you need to run `ng2-scrollreveal` is the core js file of `scrollrevealjs`, that must be installed as dependency via:
```
npm install --save scrollreveal
```
Is that the case? if yes,  what issues are you having when missing the `@types/scrollreveal`?
Besides, which bundler/loader are you using, SystemJS , Webpack or other?
Are you using `angular-cli` ? Which version?

**Comment by pryanwong** [comment]
I tried running the ng2-scrollreveal using webpack.  It would work properly but give warnings that the typedefs were not found on startup.  When I did the same thing using Systemjs it would not work.

In both cases when the typedefs were added the warnings went away.  I will close the issue.  Thanks for your response.

**Comment by tinesoft** [comment]
No problem!

I've updated the documentation to mention installing the typings for `Scrollreveal JS` to avoid theses warnings.

Cheers!
